#sudo apt-get install ruby 2.1.7

  - name: install ruby 2.1.7
    shell: >
      sudo apt-get -y update;
      sudo apt-get -y install build-essential zlib1g-dev libssl-dev libreadline6-dev libyaml-dev;
      cd /tmp;
      wget http://ftp.ruby-lang.org/pub/ruby/2.1/ruby-2.1.7.tar.gz;
      tar -xvzf ruby-2.1.7.tar.gz;
      cd ruby-2.1.7/;
      ./configure --prefix=/usr/local;
      make;
      sudo make install;
