---

# plugins
# https://github.com/sensu-plugins/sensu-plugins-docker


# install gems

docker-api
net_http_unix


# examples
#  check that a Docker container is running
# ruby check-container.rb -h /run/docker.sock -c nginx-front

# ruby metrics-docker-container.rb -H unix:///run/docker.sock
# ruby metrics-docker-stats.rb -p unix -H /run/docker.sock -c nginx-front



### sensu for node

# plugins
  - name: copy plugins
    template: src=plugins/{{item}} dest=/etc/sensu/plugins/{{item}} owner=vagrant group=vagrant mode=0775
    with_items:
      - metrics-cpu.rb
      - metrics-memory.rb



### !!! restart sensu
